version: '3'

services:

  python3:
    image: python:3.8
    command: sleep infinity
    working_dir: /src
    volumes:
      - .:/src
    links:
      - redis-server
    environment:
      - REDIS_HOST=redis-server

  python2:
    image: python:2.7
    command: sleep infinity
    working_dir: /src
    volumes:
      - .:/src
    links:
      - redis-server
    environment:
      - REDIS_HOST=redis-server

  redis-server:
    image: redis
