// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interfaces.proto

package gutter;

public final class Interfaces {
  private Interfaces() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConditionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string argument = 1;
    /**
     * <code>required string argument = 1;</code>
     */
    boolean hasArgument();
    /**
     * <code>required string argument = 1;</code>
     */
    java.lang.String getArgument();
    /**
     * <code>required string argument = 1;</code>
     */
    com.google.protobuf.ByteString
        getArgumentBytes();

    // required string attribute = 2;
    /**
     * <code>required string attribute = 2;</code>
     */
    boolean hasAttribute();
    /**
     * <code>required string attribute = 2;</code>
     */
    java.lang.String getAttribute();
    /**
     * <code>required string attribute = 2;</code>
     */
    com.google.protobuf.ByteString
        getAttributeBytes();

    // required string operator = 3;
    /**
     * <code>required string operator = 3;</code>
     */
    boolean hasOperator();
    /**
     * <code>required string operator = 3;</code>
     */
    java.lang.String getOperator();
    /**
     * <code>required string operator = 3;</code>
     */
    com.google.protobuf.ByteString
        getOperatorBytes();

    // required bool negative = 4;
    /**
     * <code>required bool negative = 4;</code>
     */
    boolean hasNegative();
    /**
     * <code>required bool negative = 4;</code>
     */
    boolean getNegative();
  }
  /**
   * Protobuf type {@code gutter.Condition}
   */
  public static final class Condition extends
      com.google.protobuf.GeneratedMessage
      implements ConditionOrBuilder {
    // Use Condition.newBuilder() to construct.
    private Condition(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Condition(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Condition defaultInstance;
    public static Condition getDefaultInstance() {
      return defaultInstance;
    }

    public Condition getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Condition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              argument_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              attribute_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              operator_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              negative_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gutter.Interfaces.internal_static_gutter_Condition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gutter.Interfaces.internal_static_gutter_Condition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gutter.Interfaces.Condition.class, gutter.Interfaces.Condition.Builder.class);
    }

    public static com.google.protobuf.Parser<Condition> PARSER =
        new com.google.protobuf.AbstractParser<Condition>() {
      public Condition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Condition(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Condition> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string argument = 1;
    public static final int ARGUMENT_FIELD_NUMBER = 1;
    private java.lang.Object argument_;
    /**
     * <code>required string argument = 1;</code>
     */
    public boolean hasArgument() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string argument = 1;</code>
     */
    public java.lang.String getArgument() {
      java.lang.Object ref = argument_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          argument_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string argument = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArgumentBytes() {
      java.lang.Object ref = argument_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        argument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string attribute = 2;
    public static final int ATTRIBUTE_FIELD_NUMBER = 2;
    private java.lang.Object attribute_;
    /**
     * <code>required string attribute = 2;</code>
     */
    public boolean hasAttribute() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string attribute = 2;</code>
     */
    public java.lang.String getAttribute() {
      java.lang.Object ref = attribute_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attribute_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string attribute = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAttributeBytes() {
      java.lang.Object ref = attribute_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attribute_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string operator = 3;
    public static final int OPERATOR_FIELD_NUMBER = 3;
    private java.lang.Object operator_;
    /**
     * <code>required string operator = 3;</code>
     */
    public boolean hasOperator() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string operator = 3;</code>
     */
    public java.lang.String getOperator() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operator_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string operator = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool negative = 4;
    public static final int NEGATIVE_FIELD_NUMBER = 4;
    private boolean negative_;
    /**
     * <code>required bool negative = 4;</code>
     */
    public boolean hasNegative() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool negative = 4;</code>
     */
    public boolean getNegative() {
      return negative_;
    }

    private void initFields() {
      argument_ = "";
      attribute_ = "";
      operator_ = "";
      negative_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasArgument()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttribute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNegative()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getArgumentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAttributeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOperatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, negative_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getArgumentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAttributeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOperatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, negative_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gutter.Interfaces.Condition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gutter.Interfaces.Condition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gutter.Interfaces.Condition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gutter.Interfaces.Condition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gutter.Interfaces.Condition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gutter.Interfaces.Condition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gutter.Interfaces.Condition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gutter.Interfaces.Condition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gutter.Interfaces.Condition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gutter.Interfaces.Condition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gutter.Interfaces.Condition prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gutter.Condition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gutter.Interfaces.ConditionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gutter.Interfaces.internal_static_gutter_Condition_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gutter.Interfaces.internal_static_gutter_Condition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gutter.Interfaces.Condition.class, gutter.Interfaces.Condition.Builder.class);
      }

      // Construct using gutter.Interfaces.Condition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        argument_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        attribute_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        operator_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        negative_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gutter.Interfaces.internal_static_gutter_Condition_descriptor;
      }

      public gutter.Interfaces.Condition getDefaultInstanceForType() {
        return gutter.Interfaces.Condition.getDefaultInstance();
      }

      public gutter.Interfaces.Condition build() {
        gutter.Interfaces.Condition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gutter.Interfaces.Condition buildPartial() {
        gutter.Interfaces.Condition result = new gutter.Interfaces.Condition(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.argument_ = argument_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attribute_ = attribute_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.operator_ = operator_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.negative_ = negative_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gutter.Interfaces.Condition) {
          return mergeFrom((gutter.Interfaces.Condition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gutter.Interfaces.Condition other) {
        if (other == gutter.Interfaces.Condition.getDefaultInstance()) return this;
        if (other.hasArgument()) {
          bitField0_ |= 0x00000001;
          argument_ = other.argument_;
          onChanged();
        }
        if (other.hasAttribute()) {
          bitField0_ |= 0x00000002;
          attribute_ = other.attribute_;
          onChanged();
        }
        if (other.hasOperator()) {
          bitField0_ |= 0x00000004;
          operator_ = other.operator_;
          onChanged();
        }
        if (other.hasNegative()) {
          setNegative(other.getNegative());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArgument()) {
          
          return false;
        }
        if (!hasAttribute()) {
          
          return false;
        }
        if (!hasOperator()) {
          
          return false;
        }
        if (!hasNegative()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gutter.Interfaces.Condition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gutter.Interfaces.Condition) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string argument = 1;
      private java.lang.Object argument_ = "";
      /**
       * <code>required string argument = 1;</code>
       */
      public boolean hasArgument() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string argument = 1;</code>
       */
      public java.lang.String getArgument() {
        java.lang.Object ref = argument_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          argument_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string argument = 1;</code>
       */
      public com.google.protobuf.ByteString
          getArgumentBytes() {
        java.lang.Object ref = argument_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          argument_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string argument = 1;</code>
       */
      public Builder setArgument(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        argument_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string argument = 1;</code>
       */
      public Builder clearArgument() {
        bitField0_ = (bitField0_ & ~0x00000001);
        argument_ = getDefaultInstance().getArgument();
        onChanged();
        return this;
      }
      /**
       * <code>required string argument = 1;</code>
       */
      public Builder setArgumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        argument_ = value;
        onChanged();
        return this;
      }

      // required string attribute = 2;
      private java.lang.Object attribute_ = "";
      /**
       * <code>required string attribute = 2;</code>
       */
      public boolean hasAttribute() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string attribute = 2;</code>
       */
      public java.lang.String getAttribute() {
        java.lang.Object ref = attribute_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          attribute_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string attribute = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAttributeBytes() {
        java.lang.Object ref = attribute_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attribute_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string attribute = 2;</code>
       */
      public Builder setAttribute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attribute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string attribute = 2;</code>
       */
      public Builder clearAttribute() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attribute_ = getDefaultInstance().getAttribute();
        onChanged();
        return this;
      }
      /**
       * <code>required string attribute = 2;</code>
       */
      public Builder setAttributeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attribute_ = value;
        onChanged();
        return this;
      }

      // required string operator = 3;
      private java.lang.Object operator_ = "";
      /**
       * <code>required string operator = 3;</code>
       */
      public boolean hasOperator() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string operator = 3;</code>
       */
      public java.lang.String getOperator() {
        java.lang.Object ref = operator_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          operator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string operator = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        java.lang.Object ref = operator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string operator = 3;</code>
       */
      public Builder setOperator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        operator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string operator = 3;</code>
       */
      public Builder clearOperator() {
        bitField0_ = (bitField0_ & ~0x00000004);
        operator_ = getDefaultInstance().getOperator();
        onChanged();
        return this;
      }
      /**
       * <code>required string operator = 3;</code>
       */
      public Builder setOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        operator_ = value;
        onChanged();
        return this;
      }

      // required bool negative = 4;
      private boolean negative_ ;
      /**
       * <code>required bool negative = 4;</code>
       */
      public boolean hasNegative() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool negative = 4;</code>
       */
      public boolean getNegative() {
        return negative_;
      }
      /**
       * <code>required bool negative = 4;</code>
       */
      public Builder setNegative(boolean value) {
        bitField0_ |= 0x00000008;
        negative_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool negative = 4;</code>
       */
      public Builder clearNegative() {
        bitField0_ = (bitField0_ & ~0x00000008);
        negative_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gutter.Condition)
    }

    static {
      defaultInstance = new Condition(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gutter.Condition)
  }

  public interface ConditionListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .gutter.ConditionList.Quantifier quantifier = 1;
    /**
     * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
     */
    boolean hasQuantifier();
    /**
     * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
     */
    gutter.Interfaces.ConditionList.Quantifier getQuantifier();

    // repeated .gutter.Condition conditions = 2;
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    java.util.List<gutter.Interfaces.Condition> 
        getConditionsList();
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    gutter.Interfaces.Condition getConditions(int index);
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    int getConditionsCount();
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    java.util.List<? extends gutter.Interfaces.ConditionOrBuilder> 
        getConditionsOrBuilderList();
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    gutter.Interfaces.ConditionOrBuilder getConditionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gutter.ConditionList}
   */
  public static final class ConditionList extends
      com.google.protobuf.GeneratedMessage
      implements ConditionListOrBuilder {
    // Use ConditionList.newBuilder() to construct.
    private ConditionList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConditionList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConditionList defaultInstance;
    public static ConditionList getDefaultInstance() {
      return defaultInstance;
    }

    public ConditionList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConditionList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gutter.Interfaces.ConditionList.Quantifier value = gutter.Interfaces.ConditionList.Quantifier.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                quantifier_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                conditions_ = new java.util.ArrayList<gutter.Interfaces.Condition>();
                mutable_bitField0_ |= 0x00000002;
              }
              conditions_.add(input.readMessage(gutter.Interfaces.Condition.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          conditions_ = java.util.Collections.unmodifiableList(conditions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gutter.Interfaces.internal_static_gutter_ConditionList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gutter.Interfaces.internal_static_gutter_ConditionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gutter.Interfaces.ConditionList.class, gutter.Interfaces.ConditionList.Builder.class);
    }

    public static com.google.protobuf.Parser<ConditionList> PARSER =
        new com.google.protobuf.AbstractParser<ConditionList>() {
      public ConditionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConditionList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConditionList> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code gutter.ConditionList.Quantifier}
     */
    public enum Quantifier
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ANY = 1;</code>
       */
      ANY(0, 1),
      /**
       * <code>ALL = 2;</code>
       */
      ALL(1, 2),
      ;

      /**
       * <code>ANY = 1;</code>
       */
      public static final int ANY_VALUE = 1;
      /**
       * <code>ALL = 2;</code>
       */
      public static final int ALL_VALUE = 2;


      public final int getNumber() { return value; }

      public static Quantifier valueOf(int value) {
        switch (value) {
          case 1: return ANY;
          case 2: return ALL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Quantifier>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Quantifier>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Quantifier>() {
              public Quantifier findValueByNumber(int number) {
                return Quantifier.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gutter.Interfaces.ConditionList.getDescriptor().getEnumTypes().get(0);
      }

      private static final Quantifier[] VALUES = values();

      public static Quantifier valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Quantifier(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:gutter.ConditionList.Quantifier)
    }

    private int bitField0_;
    // required .gutter.ConditionList.Quantifier quantifier = 1;
    public static final int QUANTIFIER_FIELD_NUMBER = 1;
    private gutter.Interfaces.ConditionList.Quantifier quantifier_;
    /**
     * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
     */
    public boolean hasQuantifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
     */
    public gutter.Interfaces.ConditionList.Quantifier getQuantifier() {
      return quantifier_;
    }

    // repeated .gutter.Condition conditions = 2;
    public static final int CONDITIONS_FIELD_NUMBER = 2;
    private java.util.List<gutter.Interfaces.Condition> conditions_;
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    public java.util.List<gutter.Interfaces.Condition> getConditionsList() {
      return conditions_;
    }
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    public java.util.List<? extends gutter.Interfaces.ConditionOrBuilder> 
        getConditionsOrBuilderList() {
      return conditions_;
    }
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    public int getConditionsCount() {
      return conditions_.size();
    }
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    public gutter.Interfaces.Condition getConditions(int index) {
      return conditions_.get(index);
    }
    /**
     * <code>repeated .gutter.Condition conditions = 2;</code>
     */
    public gutter.Interfaces.ConditionOrBuilder getConditionsOrBuilder(
        int index) {
      return conditions_.get(index);
    }

    private void initFields() {
      quantifier_ = gutter.Interfaces.ConditionList.Quantifier.ANY;
      conditions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasQuantifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getConditionsCount(); i++) {
        if (!getConditions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, quantifier_.getNumber());
      }
      for (int i = 0; i < conditions_.size(); i++) {
        output.writeMessage(2, conditions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, quantifier_.getNumber());
      }
      for (int i = 0; i < conditions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, conditions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gutter.Interfaces.ConditionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gutter.Interfaces.ConditionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gutter.Interfaces.ConditionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gutter.Interfaces.ConditionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gutter.Interfaces.ConditionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gutter.Interfaces.ConditionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gutter.Interfaces.ConditionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gutter.Interfaces.ConditionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gutter.Interfaces.ConditionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gutter.Interfaces.ConditionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gutter.Interfaces.ConditionList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gutter.ConditionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gutter.Interfaces.ConditionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gutter.Interfaces.internal_static_gutter_ConditionList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gutter.Interfaces.internal_static_gutter_ConditionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gutter.Interfaces.ConditionList.class, gutter.Interfaces.ConditionList.Builder.class);
      }

      // Construct using gutter.Interfaces.ConditionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConditionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        quantifier_ = gutter.Interfaces.ConditionList.Quantifier.ANY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (conditionsBuilder_ == null) {
          conditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          conditionsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gutter.Interfaces.internal_static_gutter_ConditionList_descriptor;
      }

      public gutter.Interfaces.ConditionList getDefaultInstanceForType() {
        return gutter.Interfaces.ConditionList.getDefaultInstance();
      }

      public gutter.Interfaces.ConditionList build() {
        gutter.Interfaces.ConditionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gutter.Interfaces.ConditionList buildPartial() {
        gutter.Interfaces.ConditionList result = new gutter.Interfaces.ConditionList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.quantifier_ = quantifier_;
        if (conditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            conditions_ = java.util.Collections.unmodifiableList(conditions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.conditions_ = conditions_;
        } else {
          result.conditions_ = conditionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gutter.Interfaces.ConditionList) {
          return mergeFrom((gutter.Interfaces.ConditionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gutter.Interfaces.ConditionList other) {
        if (other == gutter.Interfaces.ConditionList.getDefaultInstance()) return this;
        if (other.hasQuantifier()) {
          setQuantifier(other.getQuantifier());
        }
        if (conditionsBuilder_ == null) {
          if (!other.conditions_.isEmpty()) {
            if (conditions_.isEmpty()) {
              conditions_ = other.conditions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureConditionsIsMutable();
              conditions_.addAll(other.conditions_);
            }
            onChanged();
          }
        } else {
          if (!other.conditions_.isEmpty()) {
            if (conditionsBuilder_.isEmpty()) {
              conditionsBuilder_.dispose();
              conditionsBuilder_ = null;
              conditions_ = other.conditions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              conditionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConditionsFieldBuilder() : null;
            } else {
              conditionsBuilder_.addAllMessages(other.conditions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQuantifier()) {
          
          return false;
        }
        for (int i = 0; i < getConditionsCount(); i++) {
          if (!getConditions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gutter.Interfaces.ConditionList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gutter.Interfaces.ConditionList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .gutter.ConditionList.Quantifier quantifier = 1;
      private gutter.Interfaces.ConditionList.Quantifier quantifier_ = gutter.Interfaces.ConditionList.Quantifier.ANY;
      /**
       * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
       */
      public boolean hasQuantifier() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
       */
      public gutter.Interfaces.ConditionList.Quantifier getQuantifier() {
        return quantifier_;
      }
      /**
       * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
       */
      public Builder setQuantifier(gutter.Interfaces.ConditionList.Quantifier value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        quantifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gutter.ConditionList.Quantifier quantifier = 1;</code>
       */
      public Builder clearQuantifier() {
        bitField0_ = (bitField0_ & ~0x00000001);
        quantifier_ = gutter.Interfaces.ConditionList.Quantifier.ANY;
        onChanged();
        return this;
      }

      // repeated .gutter.Condition conditions = 2;
      private java.util.List<gutter.Interfaces.Condition> conditions_ =
        java.util.Collections.emptyList();
      private void ensureConditionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          conditions_ = new java.util.ArrayList<gutter.Interfaces.Condition>(conditions_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gutter.Interfaces.Condition, gutter.Interfaces.Condition.Builder, gutter.Interfaces.ConditionOrBuilder> conditionsBuilder_;

      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public java.util.List<gutter.Interfaces.Condition> getConditionsList() {
        if (conditionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(conditions_);
        } else {
          return conditionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public int getConditionsCount() {
        if (conditionsBuilder_ == null) {
          return conditions_.size();
        } else {
          return conditionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public gutter.Interfaces.Condition getConditions(int index) {
        if (conditionsBuilder_ == null) {
          return conditions_.get(index);
        } else {
          return conditionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder setConditions(
          int index, gutter.Interfaces.Condition value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.set(index, value);
          onChanged();
        } else {
          conditionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder setConditions(
          int index, gutter.Interfaces.Condition.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.set(index, builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder addConditions(gutter.Interfaces.Condition value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.add(value);
          onChanged();
        } else {
          conditionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder addConditions(
          int index, gutter.Interfaces.Condition value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionsIsMutable();
          conditions_.add(index, value);
          onChanged();
        } else {
          conditionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder addConditions(
          gutter.Interfaces.Condition.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.add(builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder addConditions(
          int index, gutter.Interfaces.Condition.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.add(index, builderForValue.build());
          onChanged();
        } else {
          conditionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder addAllConditions(
          java.lang.Iterable<? extends gutter.Interfaces.Condition> values) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          super.addAll(values, conditions_);
          onChanged();
        } else {
          conditionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder clearConditions() {
        if (conditionsBuilder_ == null) {
          conditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          conditionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public Builder removeConditions(int index) {
        if (conditionsBuilder_ == null) {
          ensureConditionsIsMutable();
          conditions_.remove(index);
          onChanged();
        } else {
          conditionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public gutter.Interfaces.Condition.Builder getConditionsBuilder(
          int index) {
        return getConditionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public gutter.Interfaces.ConditionOrBuilder getConditionsOrBuilder(
          int index) {
        if (conditionsBuilder_ == null) {
          return conditions_.get(index);  } else {
          return conditionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public java.util.List<? extends gutter.Interfaces.ConditionOrBuilder> 
           getConditionsOrBuilderList() {
        if (conditionsBuilder_ != null) {
          return conditionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(conditions_);
        }
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public gutter.Interfaces.Condition.Builder addConditionsBuilder() {
        return getConditionsFieldBuilder().addBuilder(
            gutter.Interfaces.Condition.getDefaultInstance());
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public gutter.Interfaces.Condition.Builder addConditionsBuilder(
          int index) {
        return getConditionsFieldBuilder().addBuilder(
            index, gutter.Interfaces.Condition.getDefaultInstance());
      }
      /**
       * <code>repeated .gutter.Condition conditions = 2;</code>
       */
      public java.util.List<gutter.Interfaces.Condition.Builder> 
           getConditionsBuilderList() {
        return getConditionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gutter.Interfaces.Condition, gutter.Interfaces.Condition.Builder, gutter.Interfaces.ConditionOrBuilder> 
          getConditionsFieldBuilder() {
        if (conditionsBuilder_ == null) {
          conditionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gutter.Interfaces.Condition, gutter.Interfaces.Condition.Builder, gutter.Interfaces.ConditionOrBuilder>(
                  conditions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          conditions_ = null;
        }
        return conditionsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gutter.ConditionList)
    }

    static {
      defaultInstance = new ConditionList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gutter.ConditionList)
  }

  public interface SwitchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required .gutter.Switch.State state = 2;
    /**
     * <code>required .gutter.Switch.State state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>required .gutter.Switch.State state = 2;</code>
     */
    gutter.Interfaces.Switch.State getState();

    // optional .gutter.ConditionList conditions = 3;
    /**
     * <code>optional .gutter.ConditionList conditions = 3;</code>
     */
    boolean hasConditions();
    /**
     * <code>optional .gutter.ConditionList conditions = 3;</code>
     */
    gutter.Interfaces.ConditionList getConditions();
    /**
     * <code>optional .gutter.ConditionList conditions = 3;</code>
     */
    gutter.Interfaces.ConditionListOrBuilder getConditionsOrBuilder();

    // optional string label = 4;
    /**
     * <code>optional string label = 4;</code>
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 4;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 4;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    // optional bool compounded = 5;
    /**
     * <code>optional bool compounded = 5;</code>
     */
    boolean hasCompounded();
    /**
     * <code>optional bool compounded = 5;</code>
     */
    boolean getCompounded();

    // optional bool concent = 6;
    /**
     * <code>optional bool concent = 6;</code>
     */
    boolean hasConcent();
    /**
     * <code>optional bool concent = 6;</code>
     */
    boolean getConcent();
  }
  /**
   * Protobuf type {@code gutter.Switch}
   */
  public static final class Switch extends
      com.google.protobuf.GeneratedMessage
      implements SwitchOrBuilder {
    // Use Switch.newBuilder() to construct.
    private Switch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Switch(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Switch defaultInstance;
    public static Switch getDefaultInstance() {
      return defaultInstance;
    }

    public Switch getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Switch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              gutter.Interfaces.Switch.State value = gutter.Interfaces.Switch.State.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = value;
              }
              break;
            }
            case 26: {
              gutter.Interfaces.ConditionList.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = conditions_.toBuilder();
              }
              conditions_ = input.readMessage(gutter.Interfaces.ConditionList.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(conditions_);
                conditions_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              label_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              compounded_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              concent_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gutter.Interfaces.internal_static_gutter_Switch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gutter.Interfaces.internal_static_gutter_Switch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gutter.Interfaces.Switch.class, gutter.Interfaces.Switch.Builder.class);
    }

    public static com.google.protobuf.Parser<Switch> PARSER =
        new com.google.protobuf.AbstractParser<Switch>() {
      public Switch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Switch(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Switch> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code gutter.Switch.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DISABLED = 1;</code>
       */
      DISABLED(0, 1),
      /**
       * <code>SELECTIVE = 2;</code>
       */
      SELECTIVE(1, 2),
      /**
       * <code>GLOBAL = 3;</code>
       */
      GLOBAL(2, 3),
      ;

      /**
       * <code>DISABLED = 1;</code>
       */
      public static final int DISABLED_VALUE = 1;
      /**
       * <code>SELECTIVE = 2;</code>
       */
      public static final int SELECTIVE_VALUE = 2;
      /**
       * <code>GLOBAL = 3;</code>
       */
      public static final int GLOBAL_VALUE = 3;


      public final int getNumber() { return value; }

      public static State valueOf(int value) {
        switch (value) {
          case 1: return DISABLED;
          case 2: return SELECTIVE;
          case 3: return GLOBAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<State>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gutter.Interfaces.Switch.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private State(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:gutter.Switch.State)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .gutter.Switch.State state = 2;
    public static final int STATE_FIELD_NUMBER = 2;
    private gutter.Interfaces.Switch.State state_;
    /**
     * <code>required .gutter.Switch.State state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .gutter.Switch.State state = 2;</code>
     */
    public gutter.Interfaces.Switch.State getState() {
      return state_;
    }

    // optional .gutter.ConditionList conditions = 3;
    public static final int CONDITIONS_FIELD_NUMBER = 3;
    private gutter.Interfaces.ConditionList conditions_;
    /**
     * <code>optional .gutter.ConditionList conditions = 3;</code>
     */
    public boolean hasConditions() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .gutter.ConditionList conditions = 3;</code>
     */
    public gutter.Interfaces.ConditionList getConditions() {
      return conditions_;
    }
    /**
     * <code>optional .gutter.ConditionList conditions = 3;</code>
     */
    public gutter.Interfaces.ConditionListOrBuilder getConditionsOrBuilder() {
      return conditions_;
    }

    // optional string label = 4;
    public static final int LABEL_FIELD_NUMBER = 4;
    private java.lang.Object label_;
    /**
     * <code>optional string label = 4;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string label = 4;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string label = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool compounded = 5;
    public static final int COMPOUNDED_FIELD_NUMBER = 5;
    private boolean compounded_;
    /**
     * <code>optional bool compounded = 5;</code>
     */
    public boolean hasCompounded() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool compounded = 5;</code>
     */
    public boolean getCompounded() {
      return compounded_;
    }

    // optional bool concent = 6;
    public static final int CONCENT_FIELD_NUMBER = 6;
    private boolean concent_;
    /**
     * <code>optional bool concent = 6;</code>
     */
    public boolean hasConcent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool concent = 6;</code>
     */
    public boolean getConcent() {
      return concent_;
    }

    private void initFields() {
      name_ = "";
      state_ = gutter.Interfaces.Switch.State.DISABLED;
      conditions_ = gutter.Interfaces.ConditionList.getDefaultInstance();
      label_ = "";
      compounded_ = false;
      concent_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasConditions()) {
        if (!getConditions().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, conditions_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLabelBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, compounded_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, concent_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, conditions_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLabelBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, compounded_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, concent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gutter.Interfaces.Switch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gutter.Interfaces.Switch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gutter.Interfaces.Switch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gutter.Interfaces.Switch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gutter.Interfaces.Switch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gutter.Interfaces.Switch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gutter.Interfaces.Switch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gutter.Interfaces.Switch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gutter.Interfaces.Switch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gutter.Interfaces.Switch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gutter.Interfaces.Switch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gutter.Switch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gutter.Interfaces.SwitchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gutter.Interfaces.internal_static_gutter_Switch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gutter.Interfaces.internal_static_gutter_Switch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gutter.Interfaces.Switch.class, gutter.Interfaces.Switch.Builder.class);
      }

      // Construct using gutter.Interfaces.Switch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConditionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = gutter.Interfaces.Switch.State.DISABLED;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (conditionsBuilder_ == null) {
          conditions_ = gutter.Interfaces.ConditionList.getDefaultInstance();
        } else {
          conditionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        compounded_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        concent_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gutter.Interfaces.internal_static_gutter_Switch_descriptor;
      }

      public gutter.Interfaces.Switch getDefaultInstanceForType() {
        return gutter.Interfaces.Switch.getDefaultInstance();
      }

      public gutter.Interfaces.Switch build() {
        gutter.Interfaces.Switch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gutter.Interfaces.Switch buildPartial() {
        gutter.Interfaces.Switch result = new gutter.Interfaces.Switch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (conditionsBuilder_ == null) {
          result.conditions_ = conditions_;
        } else {
          result.conditions_ = conditionsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.compounded_ = compounded_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.concent_ = concent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gutter.Interfaces.Switch) {
          return mergeFrom((gutter.Interfaces.Switch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gutter.Interfaces.Switch other) {
        if (other == gutter.Interfaces.Switch.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasConditions()) {
          mergeConditions(other.getConditions());
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000008;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasCompounded()) {
          setCompounded(other.getCompounded());
        }
        if (other.hasConcent()) {
          setConcent(other.getConcent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (hasConditions()) {
          if (!getConditions().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gutter.Interfaces.Switch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gutter.Interfaces.Switch) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required .gutter.Switch.State state = 2;
      private gutter.Interfaces.Switch.State state_ = gutter.Interfaces.Switch.State.DISABLED;
      /**
       * <code>required .gutter.Switch.State state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .gutter.Switch.State state = 2;</code>
       */
      public gutter.Interfaces.Switch.State getState() {
        return state_;
      }
      /**
       * <code>required .gutter.Switch.State state = 2;</code>
       */
      public Builder setState(gutter.Interfaces.Switch.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gutter.Switch.State state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = gutter.Interfaces.Switch.State.DISABLED;
        onChanged();
        return this;
      }

      // optional .gutter.ConditionList conditions = 3;
      private gutter.Interfaces.ConditionList conditions_ = gutter.Interfaces.ConditionList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gutter.Interfaces.ConditionList, gutter.Interfaces.ConditionList.Builder, gutter.Interfaces.ConditionListOrBuilder> conditionsBuilder_;
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public boolean hasConditions() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public gutter.Interfaces.ConditionList getConditions() {
        if (conditionsBuilder_ == null) {
          return conditions_;
        } else {
          return conditionsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public Builder setConditions(gutter.Interfaces.ConditionList value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          conditions_ = value;
          onChanged();
        } else {
          conditionsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public Builder setConditions(
          gutter.Interfaces.ConditionList.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          conditions_ = builderForValue.build();
          onChanged();
        } else {
          conditionsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public Builder mergeConditions(gutter.Interfaces.ConditionList value) {
        if (conditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              conditions_ != gutter.Interfaces.ConditionList.getDefaultInstance()) {
            conditions_ =
              gutter.Interfaces.ConditionList.newBuilder(conditions_).mergeFrom(value).buildPartial();
          } else {
            conditions_ = value;
          }
          onChanged();
        } else {
          conditionsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public Builder clearConditions() {
        if (conditionsBuilder_ == null) {
          conditions_ = gutter.Interfaces.ConditionList.getDefaultInstance();
          onChanged();
        } else {
          conditionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public gutter.Interfaces.ConditionList.Builder getConditionsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getConditionsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      public gutter.Interfaces.ConditionListOrBuilder getConditionsOrBuilder() {
        if (conditionsBuilder_ != null) {
          return conditionsBuilder_.getMessageOrBuilder();
        } else {
          return conditions_;
        }
      }
      /**
       * <code>optional .gutter.ConditionList conditions = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gutter.Interfaces.ConditionList, gutter.Interfaces.ConditionList.Builder, gutter.Interfaces.ConditionListOrBuilder> 
          getConditionsFieldBuilder() {
        if (conditionsBuilder_ == null) {
          conditionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gutter.Interfaces.ConditionList, gutter.Interfaces.ConditionList.Builder, gutter.Interfaces.ConditionListOrBuilder>(
                  conditions_,
                  getParentForChildren(),
                  isClean());
          conditions_ = null;
        }
        return conditionsBuilder_;
      }

      // optional string label = 4;
      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 4;</code>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string label = 4;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 4;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 4;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 4;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        label_ = value;
        onChanged();
        return this;
      }

      // optional bool compounded = 5;
      private boolean compounded_ ;
      /**
       * <code>optional bool compounded = 5;</code>
       */
      public boolean hasCompounded() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool compounded = 5;</code>
       */
      public boolean getCompounded() {
        return compounded_;
      }
      /**
       * <code>optional bool compounded = 5;</code>
       */
      public Builder setCompounded(boolean value) {
        bitField0_ |= 0x00000010;
        compounded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool compounded = 5;</code>
       */
      public Builder clearCompounded() {
        bitField0_ = (bitField0_ & ~0x00000010);
        compounded_ = false;
        onChanged();
        return this;
      }

      // optional bool concent = 6;
      private boolean concent_ ;
      /**
       * <code>optional bool concent = 6;</code>
       */
      public boolean hasConcent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool concent = 6;</code>
       */
      public boolean getConcent() {
        return concent_;
      }
      /**
       * <code>optional bool concent = 6;</code>
       */
      public Builder setConcent(boolean value) {
        bitField0_ |= 0x00000020;
        concent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool concent = 6;</code>
       */
      public Builder clearConcent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        concent_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gutter.Switch)
    }

    static {
      defaultInstance = new Switch(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gutter.Switch)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gutter_Condition_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gutter_Condition_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gutter_ConditionList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gutter_ConditionList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gutter_Switch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gutter_Switch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020interfaces.proto\022\006gutter\"T\n\tCondition\022" +
      "\020\n\010argument\030\001 \002(\t\022\021\n\tattribute\030\002 \002(\t\022\020\n\010" +
      "operator\030\003 \002(\t\022\020\n\010negative\030\004 \002(\010\"\214\001\n\rCon" +
      "ditionList\0224\n\nquantifier\030\001 \002(\0162 .gutter." +
      "ConditionList.Quantifier\022%\n\nconditions\030\002" +
      " \003(\0132\021.gutter.Condition\"\036\n\nQuantifier\022\007\n" +
      "\003ANY\020\001\022\007\n\003ALL\020\002\"\314\001\n\006Switch\022\014\n\004name\030\001 \002(\t" +
      "\022#\n\005state\030\002 \002(\0162\024.gutter.Switch.State\022)\n" +
      "\nconditions\030\003 \001(\0132\025.gutter.ConditionList" +
      "\022\r\n\005label\030\004 \001(\t\022\022\n\ncompounded\030\005 \001(\010\022\017\n\007c",
      "oncent\030\006 \001(\010\"0\n\005State\022\014\n\010DISABLED\020\001\022\r\n\tS" +
      "ELECTIVE\020\002\022\n\n\006GLOBAL\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gutter_Condition_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gutter_Condition_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gutter_Condition_descriptor,
              new java.lang.String[] { "Argument", "Attribute", "Operator", "Negative", });
          internal_static_gutter_ConditionList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gutter_ConditionList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gutter_ConditionList_descriptor,
              new java.lang.String[] { "Quantifier", "Conditions", });
          internal_static_gutter_Switch_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gutter_Switch_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gutter_Switch_descriptor,
              new java.lang.String[] { "Name", "State", "Conditions", "Label", "Compounded", "Concent", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
