# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interfaces.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interfaces.proto',
  package='gutter',
  serialized_pb='\n\x10interfaces.proto\x12\x06gutter\"T\n\tCondition\x12\x10\n\x08\x61rgument\x18\x01 \x02(\t\x12\x11\n\tattribute\x18\x02 \x02(\t\x12\x10\n\x08operator\x18\x03 \x02(\t\x12\x10\n\x08negative\x18\x04 \x02(\x08\"\x8c\x01\n\rConditionList\x12\x34\n\nquantifier\x18\x01 \x02(\x0e\x32 .gutter.ConditionList.Quantifier\x12%\n\nconditions\x18\x02 \x03(\x0b\x32\x11.gutter.Condition\"\x1e\n\nQuantifier\x12\x07\n\x03\x41NY\x10\x01\x12\x07\n\x03\x41LL\x10\x02\"\xcc\x01\n\x06Switch\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05label\x18\x02 \x02(\t\x12#\n\x05state\x18\x03 \x02(\x0e\x32\x14.gutter.Switch.State\x12)\n\nconditions\x18\x04 \x02(\x0b\x32\x15.gutter.ConditionList\x12\x12\n\ncompounded\x18\x05 \x02(\x08\x12\x0f\n\x07\x63oncent\x18\x06 \x02(\x08\"0\n\x05State\x12\x0c\n\x08\x44ISABLED\x10\x01\x12\r\n\tSELECTIVE\x10\x02\x12\n\n\x06GLOBAL\x10\x03')



_CONDITIONLIST_QUANTIFIER = _descriptor.EnumDescriptor(
  name='Quantifier',
  full_name='gutter.ConditionList.Quantifier',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALL', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=225,
  serialized_end=255,
)

_SWITCH_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='gutter.Switch.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELECTIVE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOBAL', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=414,
  serialized_end=462,
)


_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='gutter.Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='argument', full_name='gutter.Condition.argument', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='gutter.Condition.attribute', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operator', full_name='gutter.Condition.operator', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='negative', full_name='gutter.Condition.negative', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=112,
)


_CONDITIONLIST = _descriptor.Descriptor(
  name='ConditionList',
  full_name='gutter.ConditionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantifier', full_name='gutter.ConditionList.quantifier', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='gutter.ConditionList.conditions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONDITIONLIST_QUANTIFIER,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=255,
)


_SWITCH = _descriptor.Descriptor(
  name='Switch',
  full_name='gutter.Switch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gutter.Switch.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='gutter.Switch.label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='gutter.Switch.state', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='gutter.Switch.conditions', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compounded', full_name='gutter.Switch.compounded', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='concent', full_name='gutter.Switch.concent', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SWITCH_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=258,
  serialized_end=462,
)

_CONDITIONLIST.fields_by_name['quantifier'].enum_type = _CONDITIONLIST_QUANTIFIER
_CONDITIONLIST.fields_by_name['conditions'].message_type = _CONDITION
_CONDITIONLIST_QUANTIFIER.containing_type = _CONDITIONLIST;
_SWITCH.fields_by_name['state'].enum_type = _SWITCH_STATE
_SWITCH.fields_by_name['conditions'].message_type = _CONDITIONLIST
_SWITCH_STATE.containing_type = _SWITCH;
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
DESCRIPTOR.message_types_by_name['ConditionList'] = _CONDITIONLIST
DESCRIPTOR.message_types_by_name['Switch'] = _SWITCH

class Condition(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONDITION

  # @@protoc_insertion_point(class_scope:gutter.Condition)

class ConditionList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONDITIONLIST

  # @@protoc_insertion_point(class_scope:gutter.ConditionList)

class Switch(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SWITCH

  # @@protoc_insertion_point(class_scope:gutter.Switch)


# @@protoc_insertion_point(module_scope)
